# Generated by Django 3.2.4 on 2021-06-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalcourses', '0002_auto_20210615_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='Started from'),
        ),
    ]
