# Generated by Django 3.2.4 on 2021-06-15 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('technicalcourses', '0004_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 8, 48, 12, 224149, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
